env:
  TERM: xterm-256color

colors:
  primary:
    background: '#0b1f41'
    foreground: '#B3B1AD'
  cursor:
    cursor: '#ffcc66'
    text: '#0b1f41'

  normal:
    black: '#01060E'
    red: '#EA6C73'
    green: '#91B362'
    yellow: '#F9AF4F'
    blue: '#53BDFA'
    magenta: '#FAE994'
    cyan: '#90E1C6'
    white: '#C7C7C7'

  bright:
    black: '#686868'
    red: '#F07178'
    green: '#C2D94C'
    yellow: '#FFB454'
    blue: '#59C2FF'
    magenta: '#FFEE99'
    cyan: '#95E6CB'
    white: '#FFFFFF'

font:
  normal:
    family: 'FiraCode Nerd Font'
    style: Regular
  bold:
    family: 'FiraCode Nerd Font'
    style: Bold
  italic:
    family: 'FiraCode Nerd Font'
    style: Italic
  size: 14.0

key_bindings:
  - {key: Key6, mods: Control, chars: "\x1e"}

shell:
  program: /bin/zsh
  args:
    - --login

scrolling:
  history: 10000
  multiplier: 3
