prSections:
- title: My Pull Requests
  filters: is:open author:@me
- title: Needs My Review
  filters: is:open review-requested:@me
- title: Involved
  filters: is:open involves:@me -author:@me
issuesSections:
- title: My Issues
  filters: is:open author:@me
- title: Assigned
  filters: is:open assignee:@me
- title: Involved
  filters: is:open involves:@me -author:@me
defaults:
  preview:
    open: true
    width: 50
  prsLimit: 20
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 7
      repo:
        width: 15
      author:
        width: 15
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 16
    issues:
      updatedAt:
        width: 7
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
repoPaths: 
  :owner/:repo: ~/src/github.com/:owner/:repo
theme:
  colors:
    text:
      primary: "#cad3f5"
      secondary: "#8aadf4"
      inverted: "#181926"
      faint: "#b8c0e0"
      warning: "#ed8796"
      success: "#a6da95"
    background:
      selected: "#363a4f"
    border:
      primary: "#8aadf4"
      secondary: "#494d64"
      faint: "#363a4f"
  ui:
    sectionsShowCount: true
    table:
      showSeparator: true
pager:
  diff: ""
confirmQuit: false
keybindings:
  universal:
    - key: o 
      command: >
        tmux new-window -c {{.RepoPath}} '
          gh pr checkout {{.PrNumber}} &&
          nvim -c ":DiffviewOpen master...{{.HeadRefName}}"
        '
  issues: 
    - key: P
      command: gh issue pin {{.IssueNumber}} --repo {{.RepoName}}
  prs: []
