# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  - trigger: ":br"
    replace: "Best Regards,\nJon Snow"

  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"

  # - trigger: "::qv"
  #   replace: "
  #     #+BEGIN_QUERY\n
  #     {:title [:b \"$|$\"]\n
  #     :query [:find (pull ?b [*])\n
  #     :where\n
  #     [task ?b #{\"LATER\"}]\n
  #     ]}\n
  #     #+END_QUERY"
  #   force_clipboard: true
 
  # Or pull urls from Chrome or Safari:
  # - trigger: "llcb"
  #   replace: "{{mdurl}} #bookmark"
  #   vars:
  #     - name: mdurl
  #   type: shell
  #   params:
  #   cmd: "osascript $HOME/Library/Mobile\\ Documents/com\\~apple\\~ScriptEditor2/Documents/getUrl.scpt"
