controller: github/seclab-mrva-controller
list_file: /Users/pwntester/src/github.com/github/securitylab-code-analysis/resources/repo-lists.json
codeql_path: /Users/pwntester/src/github.com/github/codeql
