#!/usr/bin/env sh

/Users/alvaro/.sdkman/candidates/java/current/bin/java \
    -Declipse.application=org.eclipse.jdt.ls.core.id1 \
    -Dosgi.bundles.defaultStartLevel=4 \
    -Declipse.product=org.eclipse.jdt.ls.core.product \
    -Dfile.encoding=utf8 \
    -noverify \
    -Xmx1G \
    -XX:+UseG1GC \
    -XX:+UseStringDeduplication \
    -jar /Users/alvaro/.vscode/extensions/redhat.java-0.52.0/server/plugins/org.eclipse.equinox.launcher_1.5.600.v20191014-2022.jar \
    -configuration /Users/alvaro/.vscode/extensions/redhat.java-0.52.0/server/config_mac \
    -data /Users/alvaro/jdt_ws
