return {
  {
    "pwntester/nautilus.nvim",
    dev = true,
    lazy = true,
    config = function()
      require("nautilus").load {
        transparent = false,
        mode = "halcyon",
      }
    end,
  },
  {
    "catppuccin/nvim",
    lazy = true,
    name = "catppuccin",
    opts = {
      flavour = "macchiato", -- latte, frappe, macchiato, mocha
      transparent_background = false,
      show_end_of_buffer = false,
      term_colors = true,
      no_italic = false,
      no_bold = false,
      no_underline = false,
      styles = {
        comments = { "italic" },
        conditionals = { "italic" },
        loops = {},
        functions = {},
        keywords = {},
        strings = {},
        variables = {},
        numbers = {},
        booleans = {},
        properties = {},
        types = {},
        operators = {},
        -- miscs = {}, -- Uncomment to turn off hard-coded styles
      },
      -- background = {
      --   light = "latte",
      --   dark = "frappe",
      -- },
      -- dim_inactive = {
      --   enabled = true,
      --   shade = "dark",
      --   percentage = 0.1,
      -- },
      -- color_overrides = {
      --   all = {},
      --   latte = {
      --     rosewater = "#c14a4a",
      --     flamingo = "#c14a4a",
      --     red = "#c14a4a",
      --     maroon = "#c14a4a",
      --     pink = "#945e80",
      --     mauve = "#945e80",
      --     peach = "#c35e0a",
      --     yellow = "#b47109",
      --     green = "#6c782e",
      --     teal = "#4c7a5d",
      --     sky = "#4c7a5d",
      --     sapphire = "#4c7a5d",
      --     blue = "#45707a",
      --     lavender = "#45707a",
      --     text = "#654735",
      --     subtext1 = "#73503c",
      --     subtext0 = "#805942",
      --     overlay2 = "#8c6249",
      --     overlay1 = "#8c856d",
      --     overlay0 = "#a69d81",
      --     surface2 = "#bfb695",
      --     surface1 = "#d1c7a3",
      --     surface0 = "#e3dec3",
      --     base = "#f9f5d7",
      --     mantle = "#f0ebce",
      --     crust = "#e8e3c8",
      --   },
      --   frappe = {
      --     rosewater = "#f2d5cf",
      --     flamingo = "#eebebe",
      --     pink = "#f4b8e4",
      --     mauve = "#ca9ee6",
      --     red = "#e78284",
      --     maroon = "#ea999c",
      --     peach = "#ef9f76",
      --     yellow = "#e5c890",
      --     green = "#a6d189",
      --     teal = "#81c8be",
      --     sky = "#99d1db",
      --     sapphire = "#85c1dc",
      --     blue = "#8caaee",
      --     lavender = "#babbf1",
      --     --text = "#c6d0f5",
      --     text = "#b5bfe2",
      --     subtext1 = "#b5bfe2",
      --     subtext0 = "#a5adce",
      --     overlay2 = "#949cbb",
      --     overlay1 = "#838ba7",
      --     overlay0 = "#737994",
      --     surface2 = "#626880",
      --     surface1 = "#51576d",
      --     surface0 = "#414559",
      --     base = "#303446",
      --     mantle = "#292c3c",
      --     crust = "#232634",
      --   },
      --   macchiato = {
      --     rosewater = "#f4dbd6",
      --     flamingo = "#f0c6c6",
      --     pink = "#f5bde6",
      --     mauve = "#c6a0f6",
      --     red = "#ed8796",
      --     maroon = "#ee99a0",
      --     peach = "#f5a97f",
      --     yellow = "#eed49f",
      --     green = "#a6da95",
      --     teal = "#8bd5ca",
      --     sky = "#91d7e3",
      --     sapphire = "#7dc4e4",
      --     blue = "#8aadf4",
      --     lavender = "#b7bdf8",
      --     text = "#b8c0e0",
      --     subtext1 = "#b8c0e0",
      --     subtext0 = "#a5adcb",
      --     overlay2 = "#939ab7",
      --     overlay1 = "#8087a2",
      --     overlay0 = "#6e738d",
      --     surface2 = "#5b6078",
      --     surface1 = "#494d64",
      --     surface0 = "#363a4f",
      --     -- base = "#24273a",
      --     -- mantle = "#1e2030",
      --     base = "#1d2433",
      --     mantle = "#171c28",
      --     crust = "#181926",
      --   },
      -- },
      -- custom_highlights = function(colors)
      --   return {
      --     ["NeoTreeWinSeparator"] = { fg = colors.base, bg = colors.base },
      --     ["CodeqlAstFocus"] = { fg = colors.mantle, bg = colors.sapphire },
      --     ["CodeqlRange"] = { fg = colors.mantle, bg = colors.sapphire },
      --     ["CodeQLWindowPicker"] = { fg = colors.man, bg = colors.sapphire },
      --     ["Identifier"] = { fg = colors.yellow },
      --     ["Special"] = { fg = colors.sapphire },
      --     ["Number"] = { fg = colors.green },
      --     ["NormalAlt"] = { fg = colors.text, bg = colors.mantle },
      --     ["@attribute"] = { fg = colors.mauve },
      --     ["@function.builtin"] = { fg = colors.mauve },
      --     ["@variable.builtin"] = { fg = colors.sky },
      --     ["TelescopePromptTitle"] = { fg = colors.base, bg = colors.sapphire },
      --   }
      -- end,
      -- -- highlight_overrides = {
      -- --   all = function(colors)
      -- --     return {}
      -- --   end,
      -- -- },
      -- integrations = {
      --   barbecue = {
      --     dim_dirname = true, -- directory name is dimmed by default
      --     bold_basename = true,
      --     dim_context = false,
      --     alt_background = false,
      --   },
      --   cmp = true,
      --   dashboard = true,
      --   gitsigns = true,
      --   harpoon = true,
      --   lsp_trouble = true,
      --   markdown = true,
      --   neotree = true,
      --   nvimtree = false,
      --   octo = true,
      --   telescope = {
      --     enabled = true,
      --     style = "nvchad",
      --   },
      --   treesitter = true,
      --   notify = false,
      --   mini = {
      --     enabled = false,
      --   },
      -- },
    },
  },
}
