lastupdatecheck: 0
recentrepos:
    - /Users/pwntester/src/github.com/bughalla/workflow-enum-action
    - /Users/pwntester/src/github.com/github/codeql-actions
    - /Users/pwntester/dotfiles
    - /Users/pwntester/src/github.com/githubsecuritylab/codeql-community-packs
    - /Users/pwntester/src/github.com/github/securitylab-code-analysis
    - /Users/pwntester/src/github.com/pwntester/octo.nvim
    - /Users/pwntester/src/github.com/github/codeql
    - /Users/pwntester/src/github.com/github/entitlements
    - /Users/pwntester/obsidian
    - /Users/pwntester/src/github.com/pwntests/actions_tests
    - /Users/pwntester/src/github.com/Bughalla/bash-parser-action
    - /Users/pwntester/src/github.com/bughalla/bughalla
    - /Users/pwntester/src/github.com/Bughalla/bughalla
    - /Users/pwntester/src/github.com/pwntester/ESPHomeProjects
    - /Users/pwntester/src/github.com/github/codeml-autofix
    - /Users/pwntester/src/github.com/GithubSecurityLab/gh-mrva
    - /Users/pwntester/src/github.com/githubsecuritylab/gh-mrva
    - /Users/pwntester/src/github.com/pwntester/codeql.nvim
    - /Users/pwntester/src/github.com/github/securitylab-codeql
    - /Users/pwntester/src/github.com/github/codeql-patch
    - /Users/pwntester/src/github.com/pwntester/nautilus.nvim
startuppopupversion: 5
lastversion: 0.44.1
customcommandshistory:
    - qa
hidecommandlog: false
ignorewhitespaceindiffview: false
diffcontextsize: 3
renamesimilaritythreshold: 50
localbranchsortorder: recency
remotebranchsortorder: alphabetical
gitlogorder: topo-order
gitlogshowgraph: always
