git_protocol: https
editor:
prompt: enabled
pager:
extensions.codeql.version: v2.8.5
aliases:
    co: pr checkout
    url: "!gh $([[ $@ == *\"pull\"* ]] && echo pr || echo issue) view $@ --json url -q '.url'"
    vimpr: "!nvim +\"Octo `gh pr view --json url -q '.url'`\""
    vim: "!nvim +\"Octo `gh url $@`\""
    needmyreview: search prs --review-requested=@me --state=open
    waitingforreview: search prs --author @me --state open --review none
    cd: ghq-cd
    clone: q
